# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b486b1c623eb0309a9649ffcce3e346657825d66de48dfb89b92b04a1acf5df924a0a8be7dba5390d27aebf0611dc5fd755893eaf09da5774e639ed9dc9476

test:
  secret_key_base: 809b6c566e1a864a182344e79d31a574e2898ce4e342ba5cae48ce7c8a5e934b9172a7efd81603778ee767a3100acaf9b6fa2f296d3435afa12c2c4b5ad58eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
